# Generated by Django 3.2.25 on 2024-08-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alredy_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='categories_count',
            field=models.TextField(default='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0'),
        ),
        migrations.AddField(
            model_name='user_book',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
