# Generated by Django 3.2.25 on 2024-08-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240823_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alredy_read',
            new_name='already_read',
        ),
    ]
