# Generated by Django 3.2.25 on 2024-08-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_books_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='books_cover',
            new_name='book_cover',
        ),
    ]
