# Generated by Django 3.2.25 on 2024-08-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_alredy_read_user_already_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='already_read',
        ),
        migrations.AddField(
            model_name='user',
            name='state_count',
            field=models.TextField(default='0 0 0'),
        ),
    ]
