# Generated by Django 3.2.25 on 2024-08-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_book_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_book',
            name='book_cover',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
